spring:
  application:
    name: eureka_server
  profiles:
    active: 6999

---
spring:
  profiles: 6999
server:
  port: 6999
eureka:
  instance:
    hostname: eureka-6999
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-6999:6999/eureka/
    fetch-registry: false
---
spring:
  profiles: 7900
server:
  port: 7900
eureka:
  instance:
    hostname: eureka-7900
  client:
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/

---
spring:
  profiles: 7901
server:
  port: 7901
eureka:
  instance:
    hostname: eureka-7901
  client:
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/,http://eureka-7902:7902/eureka/

---
spring:
  profiles: 7902
server:
  port: 7902
eureka:
  instance:
    hostname: eureka-7902
  client:
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/,http://eureka-7901:7901/eureka/





